name = "tx2"
default_byte = 0

[nodes."/"]
source = { file = "assets/tx02_regular.png", w = 16, h = 36, cols = 16 }

[[nodes."/".layers]]
bytes = [32, 126]
start = 0

[[nodes."/".layers]]
source = { file = "assets/tx02_regular_add.png", w = 16, h = 36, cols = 16 }
chars = "§↑↗→↘↓↙←↖↔↕≡+−×÷=≠><≥≤±≈∧∨¬■▲▶▼◀△▷▽◁◌◊∞·•º«»‹›₿$€₺₽₹£¥¦†‡¶øæ"
start = 0

[nodes."/:thin"]
source = { file = "assets/tx02_thin.png", w = 16, h = 36, cols = 16 }

[[nodes."/:thin".layers]]
bytes = [32, 126]
start = 0

[[nodes."/:thin".layers]]
source = { file = "assets/tx02_thin_add.png", w = 16, h = 36, cols = 16 }
chars = "§↑↗→↘↓↙←↖↔↕≡+−×÷=≠><≥≤±≈∧∨¬■▲▶▼◀△▷▽◁◌◊∞·•º«»‹›₿$€₺₽₹£¥¦†‡¶øæ"
start = 0



[nodes."/:bold"]
source = { file = "assets/tx02_bold.png", w = 16, h = 36, cols = 16 }

[[nodes."/:bold".layers]]
bytes = [32, 126]
start = 0

[[nodes."/:bold".layers]]
source = { file = "assets/tx02_bold_add.png", w = 16, h = 36, cols = 16 }
chars = "§↑↗→↘↓↙←↖↔↕≡+−×÷=≠><≥≤±≈∧∨¬■▲▶▼◀△▷▽◁◌◊∞·•º«»‹›₿$€₺₽₹£¥¦†‡¶øæ"
start = 0