name = "tx2b"
default_byte = 0

[nodes."/"]
source = { file = "assets/tx02_bold.png", w = 22, h = 35, cols = 16 }

[[nodes."/".layers]]
bytes = [32, 126]
start = 0

[[nodes."/".layers]]
chars = "§↑↗→↘↓↙←↖↔↕≡+−×÷=≠><≥≤±≈∧∨¬■▲▶▼◀△▷▽◁◌◊∞·•º«»‹›₿$€₺₽₹£¥¦†‡¶øæ"
start = 95
